name: Publish Package

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@omarsdev'
          cache: 'yarn'

      - name: Write npmrc for GitHub Packages
        run: |
          cat <<'EOF' > .npmrc
          @omarsdev:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
          always-auth=true
          EOF
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_PACKAGES_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump package version
        run: |
          npm version patch -m "chore: release %s"

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_PACKAGES_TOKEN }}

      - name: Push version bump
        run: |
          git push origin HEAD:develop --follow-tags
